create table if not exists override_reason_codes_tree(
override_reason_codes_id Integer not null,
tree_effective_date varchar(255) null,
hierarchy_name varchar(255) null,
hierarchy_version Integer null,
reason_code_hierarchy1 varchar(255) null,
reason_code_hierarchy1_desc varchar(255) null,
reason_code_hierarchy2 varchar(255) null,
reason_code_hierarchy2_desc varchar(255) null,
reason_code_hierarchy3 varchar(255) null,
reason_code_hierarchy3_desc varchar(255) null,
reason_code_hierarchy4 varchar(255) null,
reason_code_hierarchy4_desc varchar(255) null,
reason_code_hierarchy5 varchar(255) null,
reason_code_hierarchy5_desc varchar(255) null,
reason_code_hierarchy6 varchar(255) null,
reason_code_hierarchy6_desc varchar(255) null,
reason_code_hierarchy7 varchar(255) null,
reason_code_hierarchy7_desc varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint override_reason_codes_tree_pk primary key(override_reason_codes_id));

